name: Fetch Books from Trello

on:
  schedule:
    - cron: '0 0 * * *'  # Run everyday at midnight UTC
  workflow_dispatch:     # Run by hand

jobs:
  fetch-books:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch books from Trello
      env:
        ACTION: "GITHUB_ACTION"
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_OAUTH_SECRET: ${{ secrets.TRELLO_OAUTH_SECRET }}
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
      run: |
        python librarian.py --output completed_books.json --list_name Completed
        python librarian.py --output reading_books.json --list_name Reading
        python librarian.py --output shelved_books.json --list_name Shelved

    - name: Commit and push if changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add completed_books.json reading_books
        # Check for modified files
        if git diff --staged --quiet; then
          echo "No changes to books lists, skipping commit"
        else
          echo "Changes detected, creating a commit"
          git commit -m "Update books list"
          git push
        fi
